imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    translator:
        fallbacks: ["%locale%"]
        logging: false
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enabled: true, enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ VirtualniNemocniceAppBundle ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        less:
            node:       /usr/local/bin/node
            node_paths: [/usr/local/lib/node, /usr/local/lib/node_modules]
            compress:   true
            apply_to:   "\.less$"
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

braincrafted_bootstrap:
    assets_dir: %kernel.root_dir%/../bower_components/bootstrap
    auto_configure:
        assetic: false
        twig: true

# Doctrine Configuration
doctrine:
    dbal:
        default_connection: default
        connections:
            default:
              driver:   "%database_driver%"
              host:     "%database_host%"
              port:     "%database_port%"
              dbname:   "%database_name%"
              user:     "%database_user%"
              password: "%database_password%"
              charset:  UTF8
              mapping_types:
                  enum: string
            prod:
              driver:   "%database_driver%"
              host:     "%database_host_prod%"
              port:     "%database_port%"
              dbname:   "%database_name_prod%"
              user:     "%database_user_prod%"
              password: "%database_password_prod%"
              charset:  UTF8
              mapping_types:
                  enum: string
    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }
